In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
nested_list = [[1,2,3,4], [5,6,7,8], [8,7,6,5]]

In [5]:
nested_list

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 7, 6, 5]]

In [6]:
np.array(nested_list)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5]])

In [7]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.randn(10)

array([-1.20174979, -0.29411156,  0.69487877, -0.14739805,  1.29001105,
        0.61162113, -1.44324586,  0.78326434,  0.23298606, -0.87023995])

In [15]:
np.random.randn(5)

array([-1.87855705, -0.50814369, -0.27636701, -0.10328028,  0.04107371])

In [16]:
np.random.rand(3,5)

array([[0.85881375, 0.07595419, 0.77565839, 0.68838981, 0.15906962],
       [0.20246609, 0.77256185, 0.80398384, 0.20199277, 0.5332368 ],
       [0.80041282, 0.37181181, 0.27444401, 0.44347331, 0.31786157]])

In [21]:
np.random.randint(1,100,(2,3))

array([[23, 86, 99],
       [51, 95, 66]])

In [27]:
arr = np.arange(25)

In [28]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])

In [32]:
ranrr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranrr

array([21, 14,  1, 48, 43, 27, 33, 30, 43,  9])

In [36]:
arr.shape

(25,)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranrr 

array([21, 14,  1, 48, 43, 27, 33, 30, 43,  9])

In [43]:
ranrr.max()

48

In [44]:
ranrr.argmax()

3

In [45]:
ranrr.min()

1

In [46]:
ranrr.argmin()

2

In [47]:
ranrr.dtype

dtype('int32')